name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B clean package verify
      - name: Collect flatified coaches
        run: |
          mkdir -p ./target/flatified-coaches
          cp -v ./*/target/lib-*.xml ./target/flatified-coaches
      - name: Upload flatified coaches
        uses: actions/upload-artifact@v2
        with:
          name: flatified-coaches
          path: ./target/flatified-coaches/*.xml
